# -*- coding: utf-8 -*-
"""BMI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-usb4EW6zIkqiToMejR8VuHdfCG7an8J
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st

weight = float(input("Enter weight in kg: "))
height = float(input("Enter height in meters: "))

bmi = weight / (height * height)

print("Your BMI is:", bmi)

if bmi < 18.5:
    print("Underweight")
elif bmi < 24.9:
    print("Normal weight")
elif bmi < 29.9:
    print("Overweight")
else:
    print("Obese")